// <auto-generated />
using System;
using API_ExpenseManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_ExpenseManagement.Data.Migrations
{
    [DbContext(typeof(ExpenseManagementContext))]
    [Migration("20200621080240_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_ExpenseManagement.Models.Category", b =>
                {
                    b.Property<int>("Id_Cate")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageCate");

                    b.Property<string>("NameCate");

                    b.Property<int?>("TypeCategoryId");

                    b.HasKey("Id_Cate");

                    b.HasIndex("TypeCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("API_ExpenseManagement.Models.TypeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image_Type");

                    b.Property<string>("Name_Type");

                    b.Property<string>("TypeExpense");

                    b.HasKey("Id");

                    b.ToTable("TypeCategories");
                });

            modelBuilder.Entity("API_ExpenseManagement.Models.Category", b =>
                {
                    b.HasOne("API_ExpenseManagement.Models.TypeCategory")
                        .WithMany("Categories")
                        .HasForeignKey("TypeCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
